added logic
ohrimovich/nodejs-homework-rest-api pull request #2
Opened 2022-01-05 09:40 UTC by ohrimovich

2022-01-06 09:16 UTC, KirillKulakow commented on model/index.js
> +    const [contact] = contacts.filter(contact => contact.id === contactId);
переписать на find
почитай чем отличается filter от find

2022-01-06 09:17 UTC, KirillKulakow commented on model/index.js
> +const listContacts = async () => {
удалить async
https://learn.javascript.ru/async-await

2022-01-06 09:17 UTC, KirillKulakow commented on model/index.js
> +const getContactById = async (contactId) => {
удалить async
https://learn.javascript.ru/async-await

2022-01-06 09:18 UTC, KirillKulakow commented on model/index.js
> +    const updatedContact = { id: contactId, ...contacts[index], ...body }
удалить id: contactId
смысл записывать ид, если он перезаписывается здесь ...contacts[index]

2022-01-06 09:19 UTC, KirillKulakow commented on routes/api/contacts.js
> +router.put('/:id', async (req, res, next) => {
добавь сюда тоже вариацию входящих параметров как в добавлении нового контакта

2022-01-06 09:21 UTC, KirillKulakow requested changes
Need fix

2022-01-09 15:00 UTC, ohrimovich commented on routes/api/contacts.js
> +router.put('/:id', async (req, res, next) => {
Добавил

2022-01-09 15:00 UTC, ohrimovich commented on model/index.js
> +    const updatedContact = { id: contactId, ...contacts[index], ...body }
Исправил

2022-01-09 15:00 UTC, ohrimovich commented on model/index.js
> +const getContactById = async (contactId) => {
Удалил

2022-01-09 15:01 UTC, ohrimovich commented on model/index.js
> +const listContacts = async () => {
Удалил 
Спасибо

2022-01-09 15:01 UTC, ohrimovich commented on model/index.js
> +    const [contact] = contacts.filter(contact => contact.id === contactId);
Исправил

2022-01-10 19:30 UTC, KirillKulakow approved these changes

2022-01-11 13:49 UTC, merged