Add auth logic
ohrimovich/nodejs-homework-rest-api pull request #4
Opened 2022-01-18 19:05 UTC by ohrimovich

2022-01-18 20:31 UTC, KirillKulakow commented on controllers/contacts/index.js
>      res.status(HttpCode.OK).json({ status: 'sucsses', code: HttpCode.OK, data: {...contacts} })
зачем это действие? { ...contacts }

2022-01-18 20:33 UTC, KirillKulakow commented on routes/api/auth/index.js
> +
не вижу роута current

2022-01-18 20:34 UTC, KirillKulakow requested changes
need fix

2022-01-19 13:59 UTC, ohrimovich commented on controllers/contacts/index.js
>      res.status(HttpCode.OK).json({ status: 'sucsses', code: HttpCode.OK, data: {...contacts} })
Так, дійсно зайве 
Виправив

2022-01-19 14:00 UTC, ohrimovich commented on routes/api/auth/index.js
> +
Додав логіку роута current

2022-01-19 19:32 UTC, KirillKulakow approved these changes

2022-01-20 09:01 UTC, merged